export const ANSWER_MODES_SEED = [
  {
    slug: "quick",
    name: "快速回答",
    description: "日常问题、快速决策",
    instruction: `回答控制在 300 到 600 字以内。先给结论，再给 3 到 5 个关键点。不要长篇铺开，不要过度解释。`,
    maxLengthPreference: "short",
    isDefault: true,
  },
  {
    slug: "deep",
    name: "深度分析",
    description: "复杂决策、产品分析、战略分析",
    instruction: `先给结论，再分析背景、核心问题、原因、方案、风险、下一步。可以详细展开，适合复杂问题。`,
    maxLengthPreference: "long",
    isDefault: false,
  },
  {
    slug: "document",
    name: "生成文档",
    description: "PRD、方案书、申报书、说明书",
    instruction: `输出正式文档结构，逻辑完整，标题层级清楚，内容可直接复制使用。尽量减少闲聊解释。`,
    maxLengthPreference: "long",
    isDefault: false,
  },
  {
    slug: "prompt",
    name: "生成提示词",
    description: "给 Cursor、Gemini、Midjourney 等工具使用",
    instruction: `直接输出可复制提示词。说明目标、背景、任务、输出要求、约束。尽量结构化，不要只给抽象建议。`,
    maxLengthPreference: "medium",
    isDefault: false,
  },
  {
    slug: "product",
    name: "产品顾问",
    description: "创业、产品规划、MVP、商业模式",
    instruction: `优先判断用户所处阶段，优先 MVP 思维。明确 P0 / P1 / P2，帮用户做取舍，不要堆功能。输出可执行下一步。`,
    maxLengthPreference: "medium",
    isDefault: false,
  },
] as const;

export const SCENE_TEMPLATES_SEED = [
  {
    slug: "mvp",
    name: "MVP 设计模板",
    type: "product",
    description: "从想法收敛到最小可行产品",
    systemInstruction: "帮助用户定义 MVP 范围、核心用户、核心场景、验证指标与 2 周可执行计划。",
    outputStructure: "## 结论\n## 目标用户\n## 核心场景\n## MVP 功能（P0）\n## 验证指标\n## 下一步",
    isDefaultEnabled: true,
  },
  {
    slug: "prd",
    name: "PRD 生成模板",
    type: "product",
    description: "产品需求文档",
    systemInstruction: "生成结构化 PRD，包含背景、目标、用户故事、功能需求、非功能需求、里程碑。",
    outputStructure: "## 背景\n## 目标\n## 用户与场景\n## 功能需求\n## 非功能需求\n## 里程碑",
    isDefaultEnabled: true,
  },
  {
    slug: "gemini-canvas",
    name: "Gemini Canvas 原型提示词",
    type: "design",
    description: "生成可用于 Gemini Canvas 的原型描述",
    systemInstruction: "输出可直接粘贴到 Gemini Canvas 的页面结构、组件、交互和视觉描述。",
    outputStructure: "## 页面目标\n## 布局结构\n## 组件清单\n## 交互说明\n## 视觉风格",
    isDefaultEnabled: false,
  },
  {
    slug: "cursor-dev",
    name: "Cursor 开发提示词",
    type: "dev",
    description: "生成可给 Cursor 执行的开发任务",
    systemInstruction: "输出分步骤、可执行的开发提示词，包含文件范围、约束、验收标准。",
    outputStructure: "## 任务目标\n## 涉及文件\n## 实现步骤\n## 约束\n## 验收标准",
    isDefaultEnabled: true,
  },
  {
    slug: "business",
    name: "商业化分析模板",
    type: "business",
    description: "商业模式与盈利分析",
    systemInstruction: "分析目标用户、价值主张、收入模式、成本结构、竞争与风险。",
    outputStructure: "## 结论\n## 用户与痛点\n## 价值主张\n## 收入模式\n## 成本与风险\n## 下一步",
    isDefaultEnabled: false,
  },
  {
    slug: "patent",
    name: "专利交底书模板",
    type: "legal",
    description: "技术方案专利交底辅助",
    systemInstruction: "按专利交底书结构整理技术领域、背景、发明内容、实施方式。必须提示需专利代理人审核。",
    outputStructure: "## 技术领域\n## 背景技术\n## 发明内容\n## 具体实施方式\n## 边界说明",
    isDefaultEnabled: false,
  },
  {
    slug: "grant",
    name: "项目申报书模板",
    type: "document",
    description: "科研项目或政策申报",
    systemInstruction: "生成申报书框架：项目背景、目标、方案、创新点、计划、预算要点。",
    outputStructure: "## 项目背景\n## 建设目标\n## 实施方案\n## 创新点\n## 计划进度\n## 预算要点",
    isDefaultEnabled: false,
  },
  {
    slug: "urban-design",
    name: "城市设计概念模板",
    type: "design",
    description: "城市/片区设计概念梳理",
    systemInstruction: "从区位、人群、空间结构、风貌、实施策略输出设计概念。",
    outputStructure: "## 概念结论\n## 场地解读\n## 空间结构\n## 风貌策略\n## 实施建议",
    isDefaultEnabled: false,
  },
  {
    slug: "xiaohongshu",
    name: "小红书文案模板",
    type: "content",
    description: "种草/干货类小红书笔记",
    systemInstruction: "生成标题、开头钩子、正文分点、标签建议，语气自然不生硬。",
    outputStructure: "## 标题备选\n## 正文\n## 标签建议",
    isDefaultEnabled: false,
  },
  {
    slug: "code-fix",
    name: "代码解释与修复模板",
    type: "dev",
    description: "读代码、找 bug、给修复方案",
    systemInstruction: "先解释问题原因，再给修复方案与代码示例，最后给验证步骤。",
    outputStructure: "## 问题结论\n## 原因分析\n## 修复方案\n## 代码示例\n## 验证步骤",
    isDefaultEnabled: false,
  },
] as const;
